### ISSUE TITLE
Slowbro linux-vfio custom repository bad PGP signature

### ISSUE THREAD

**Issue by Swiss22** [slowbro/linux-vfio#1]
Slowbro linux-vfio custom repository bad PGP signature

Server = http://www.slowbro.org/arch/$arch/

error: slowbro: signature from "Katelyn Schiesser <katelyn.schiesser@gmail.com>" is unknown trust
error: failed to synchronize all databases (invalid or corrupted database (PGP signature))

This repo was working until about a week or so ago. Tried reimporting keys etc

**Comment by slowbro** [comment]
Ah, likely due to SKS keyservers going down. I likely need to upload my key elsewhere... do you know what keyservers you use?

**Comment by slowbro** [comment]
I uploaded my key to `hkps://keyserver.ubuntu.com` in case it wasn't there. Also, make sure that my key was imported into pacman's keyring: https://wiki.archlinux.org/title/Pacman/Package_signing#Adding_unofficial_keys

**Comment by Swiss22** [comment]
I tried adding a few of the keys from that page, same error.
This used to be working on my end

**Comment by slowbro** [comment]
Did you do the 'ltrust' bit from that page? Can you also give me the output of `gpg --list-keys katelyn.schiesser@gmail.com` ?

**Comment by Swiss22** [comment]
Thank you, I figured it out thanks for helping me narrow it down. 
I hadn't locally signed the key with pacman-key --lsign-key
Thanks for maintaining this kernel
